### ISSUE TITLE
_TypeError was thrown building RawGestureDetector(state: RawGestureDetectorState#1ad0d(gestures: [vertical drag])): type '() => Null' is not a subtype of type '(() => StoryItem)?' of 'orElse'

### ISSUE THREAD

**Issue by 0xDesolution** [awaik/flutter_instagram_stories#14]
I have been having an issue trying to use the packages when upon on click the story, it will crash straight away. I wondering if you have faced similar issues in the past or anyone of the community have the same issue.
@awaik 
```
The error I have been getting:
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building   @@RawGestureDetector(state:
RawGestureDetectorState#1ad0d(gestures: [vertical drag])):
type '() => Null' is not a subtype of type '(() => StoryItem)?' of 'orElse'

The relevant error-causing widget was:
  GestureDetector
  file:///Users/edwin/Development/flutter/.pub-cache/git/flutter_instagram_stories-eb421e9e12c7a9e6956036e0503158fe55f7b29d/lib/grouped_stories_view.dart:160:26

When the exception was thrown, this was the stack:
#0      ListMixin.firstWhere (dart:collection/list.dart)
#1      StoryViewState.initState (package:flutter_instagram_stories/story_view.dart:337:41)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
...     Normal element mounting (32 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#36     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#37     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
...     Normal element mounting (29 frames)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#71     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#80     _invoke (dart:ui/hooks.dart:163:10)
#81     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#82     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
```

<img width="350" alt="20211112-173512" src="https://user-images.githubusercontent.com/52876536/141444969-b1ca16d4-a21c-45e0-bc59-bb702846dc60.png">
<img width="1227" alt="20211112-173519" src="https://user-images.githubusercontent.com/52876536/141444981-b0271b8f-e8fe-4c4d-8481-4943126ace55.png">

<img width="1227" alt="20211112-173519" src="https://user-images.githubusercontent.com/52876536/141445492-dc8c88ee-c49c-4717-a975-1b13df41910f.png">

**Comment by MiguelAngelLopezBlanca** [comment]
Good, when I go to use the library, the same error has occurred to me, when I click on the story I get an error just like the one you show in the images.
Have you been able to fix it already?

**Comment by awaik** [comment]
Hi,
I'll try to fix it during the week (or next weekend).

**Comment by MiguelAngelLopezBlanca** [comment]
Ok, thank you

**Comment by awaik** [comment]
I've updated dependencies in the package and in the example and it works again.
I didn't change the code itself.
Please check how it works with updated package.
flutter_instagram_stories: ^1.0.1

Please pay attention to the new way of Firebase initialization
https://firebase.flutter.dev/docs/overview/#initialization


<img width="1263" alt="Screenshot 2022-02-15 at 17 20 19" src="https://user-images.githubusercontent.com/5330807/154083231-08e14e90-2824-44dd-9fda-d159cb048029.png">

**Comment by MiguelAngelLopezBlanca** [comment]
Ok, thank you. I will review and update it throughout this week or on the weekend and I'll tell you

**Comment by MiguelAngelLopezBlanca** [comment]
<img width="1352" alt="Captura de pantalla 2022-02-16 a las 17 51 03" src="https://user-images.githubusercontent.com/51151697/154315307-8281a91d-abdd-4a09-a910-d3d25aeaf56a.png">
![Captura de pantalla 2022-02-16 a las 17 51 27](https://user-images.githubusercontent.com/51151697/154315320-bd15324b-eb2d-441d-ae73-58a15ab98ba0.png)
![Captura de pantalla 2022-02-16 a las 17 51 39](https://user-images.githubusercontent.com/51151697/154315324-5a4b3073-7b5f-4ea3-82ed-03f64c786092.png)

The same thing keeps happening to me, I updated the dependencies to the version you indicated, but it keeps giving me an error. Here I attach the screenshots of it.

**Comment by MiguelAngelLopezBlanca** [comment]
The same thing keeps happening to me, I updated the dependencies to the version you indicated, but it keeps giving me an error. Here I attach the screenshots of it.

<img width="1352" alt="Captura de pantalla 2022-02-16 a las 17 51 03" src="https://user-images.githubusercontent.com/51151697/154315691-72129d97-7b1d-46fd-9ca7-6f00fc6094a8.png">

![Captura de pantalla 2022-02-16 a las 17 51 27](https://user-images.githubusercontent.com/51151697/154315753-c5ffa520-fd47-4113-952b-24f0459f03f0.png)

![Captura de pantalla 2022-02-16 a las 17 51 39](https://user-images.githubusercontent.com/51151697/154315826-ae23ff48-5f86-4bfe-8df4-b76c75249464.png)

**Comment by awaik** [comment]
It looks like wrong data in the Firestore.
Please double check fields names.

**Comment by MiguelAngelLopezBlanca** [comment]
<img width="471" alt="Captura de pantalla 2022-02-16 a las 22 59 45" src="https://user-images.githubusercontent.com/51151697/154364557-2b682043-472a-4df9-98c5-c5f0704618b7.png">

This is a screenshot of the firestore data

**Comment by MiguelAngelLopezBlanca** [comment]
Hello @awaik , have you been able to review the capture that I attached in the last comment about the name of the firestore database fields?

**Comment by awaik** [comment]
Hey @MiguelAngelLopezBlanca 
is it array in your database?

<img width="502" alt="Screenshot 2022-02-23 at 20 52 24" src="https://user-images.githubusercontent.com/5330807/155378194-a9ca3616-646c-44df-b26c-9ace0860de79.png">

**Comment by MiguelAngelLopezBlanca** [comment]
@awaik if it is an array

**Comment by MiguelAngelLopezBlanca** [comment]
![Captura de pantalla 2022-02-23 a las 21 00 05](https://user-images.githubusercontent.com/51151697/155398352-02db609e-a3c4-47fa-b812-2158716d74c2.png)

**Comment by awaik** [comment]
Can you please try to remove all `file` records and paste test one

`
"file": [
    {
      "filetype": "image",
      "url": {
        "en":
            "https://firebasestorage.googleapis.com/v0/b/flutter-instagram-stories.appspot.com/o/in31.jpg?alt=media&token=3ff0173a-0d97-4339-8136-86603f449446"
      }
    }
  ]
`

**Comment by Azattu** [comment]
Exact same issue as described by @MiguelAngelLopezBlanca

> Can you please try to remove all `file` records and paste test one
> 
> `"file": [ { "filetype": "image", "url": { "en": "https://firebasestorage.googleapis.com/v0/b/flutter-instagram-stories.appspot.com/o/in31.jpg?alt=media&token=3ff0173a-0d97-4339-8136-86603f449446" } } ]`

@awaik above This not helped

**Comment by awaik** [comment]
@MiguelAngelLopezBlanca 
Had you chance to fix it?

**Comment by awaik** [comment]
Can't find a bug, because test app with real Firestore database works. You can check it yourself, the database is open to read and `Example` folder in repo contains all the code.

https://user-images.githubusercontent.com/5330807/158007405-aabdc463-be0e-479f-bd9d-5839e57cc94d.mov

**Comment by kevinZartek** [comment]
same error for me, for the example code itself.
I used **firstWhereOrNull** instead of 'firstWhere' everywhere in 'story_view.dart', function from 'collection' package and it solved my problem.

**Comment by awaik** [comment]
Fixed with the new version, please check
flutter_instagram_stories: ^1.0.2

Thanks for the help @kevinZartek
