### ISSUE TITLE
Not showing stories

### ISSUE THREAD

**Issue by harimoradiya** [awaik/flutter_instagram_stories#15]
Is any problem with an emulator
![Screenshot_20220610_123519](https://user-images.githubusercontent.com/66943772/173009777-bf423a8b-3b06-4819-8b5b-cf8949605fdb.png)
?

**Comment by harimoradiya** [comment]
Here is my firestore database - dummy data
![Screenshot 2022-06-10 123836](https://user-images.githubusercontent.com/66943772/173010193-e6d737dc-40bf-481e-888f-7d345af1698f.png)

**Comment by awaik** [comment]
Can you please share the error log.

**Comment by awaik** [comment]
And please check `previewImage`, `previewTitle` - it seems they should be level up on the tree.

**Comment by harimoradiya** [comment]
![log](https://user-images.githubusercontent.com/66943772/173799896-6735893d-f20e-42ae-8b9d-8e828e20b0b2.png)
See

**Comment by harimoradiya** [comment]
![logcat](https://user-images.githubusercontent.com/66943772/173808747-2386070d-3daf-4d06-a3a6-2e7c52dd3e2b.png)
Also this!

**Comment by harimoradiya** [comment]
type '() => Null' is not a subtype of type '(() => StoryItem)?' of 'orElse'  😞

**Comment by awaik** [comment]
Fixed with the new version, please check
flutter_instagram_stories: ^1.0.2

**Comment by harimoradiya** [comment]
@awaik Thanks
