### ISSUE TITLE
the background

### ISSUE THREAD

**Issue by wkz9** [awaik/flutter_instagram_stories#18]
Hello. How to remove the background? transparent
![WhatsApp Image 2022-10-24 at 21 48 42](https://user-images.githubusercontent.com/77798695/197581841-e0b0754c-6659-4643-a601-07c8ef79c038.jpeg)

**Comment by awaik** [comment]
Hi!
you can find it in the example
https://github.com/awaik/flutter_instagram_stories/blob/master/example/lib/main.dart

```
           iconBoxDecoration: const BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(15.0)),
              color: Color(0xFFffffff),
              boxShadow: [
                BoxShadow(
                  color: Color(0xff333333),
                  blurRadius: 10.0,
                  offset: Offset(
                    0.0,
                    4.0,
                  ),
                ),
              ],
            ),
```

**Comment by awaik** [comment]
Thanks for the reporting.
Fixed, please update the package.
