### ISSUE TITLE
Video is not visible - but sound works (when i open the stories video not visible ).

### ISSUE THREAD

**Issue by appbooksaudio** [awaik/flutter_instagram_stories#22]
![Screenshot_1710747804](https://github.com/awaik/flutter_instagram_stories/assets/155871222/26fef7cf-0cd3-4ce8-ab0a-40a91ff8e4bd)

**Comment by HbkuPress** [comment]
![Screenshot_1710747804](https://github.com/awaik/flutter_instagram_stories/assets/155871222/4eb4972a-e599-4ea3-9efa-3138885b9b8d)

**Comment by awaik** [comment]
Can you please provide a log with errors? Otherwise, I can't find the reason for the bug.

**Comment by appbooksaudio** [comment]
Thank you for response.
I solved the issues by adding **setState** to (  playerController!.initialize() { setState(() {});});)  function  widget.videoLoader.loadVideo(); class (story_video.dart).
