### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by blackmann** [awaik/flutter_instagram_stories#6]
This library should include my license since it makes use of most of my original codebase.

As good practice, your library should make use of `story_view` package rather than copying the source over verbatim. Your implementation is great and builds upon the base functionality of `story_view`. It will be better if you rather made that separation and whatever improvements made to the `story_view` part can be shared with the original library.

I find it that this library still has the same core limitations identified in the original `story_view`. And I am skeptical of the fact that, fixes I may author in future will also just be copied over verbatim like this.

Let's do good!

**Comment by awaik** [comment]
Hello,

yes, I initially wrote in the license https://github.com/awaik/flutter_instagram_stories/blob/master/LICENSE

```
// Project was initially copied from https://github.com/blackmann/story_view
// Copyright 2019 De-Great Yartey. All rights reserved.
```

If you would like to add any info to read.me or to License - of course, I do it immediately. This package, for now, uses about 70% of the code from your package.

I thought about using your package, but I didn't find a way to provide compatibility. It is the first version and I'm going to rewrite a lot of things - to use streams and BLoC.

Thank you for the great package and please let me know what to add or to do.

**Comment by awaik** [comment]
Thank you!
I also moved this lines to the start of license and added info to read.me

> The project was initially copied from https://github.com/blackmann/story_view - great thanks for this nice package. In case you more flexible functionality you can check the original project.

https://pub.dev/packages/flutter_instagram_stories - updated with new data.

**Comment by blackmann** [comment]
Great, that's fine.

An idea about your example - instead of providing detailed argument values, you can use 
```dart
...
argumentName: ... // description of argument
```

That will make your example short and developers can refer to the documentation for extra details on type and so forth.

Great work you've done though!
