### ISSUE TITLE
Flexible ontap/gesture event

### ISSUE THREAD

**Issue by JSBmanD** [awaik/flutter_instagram_stories#7]
I can't get why you are using pushAndRemoveUntil for showing stories while it could be made by push. It will be better and less laggy as with removing all the pages now.

**Comment by awaik** [comment]
Hi,
can you please point to the file and the line of code?

**Comment by awaik** [comment]
ok, found it 
```
onTap: () async {
   _backStateAdditional = true;
   Navigator.pushAndRemoveUntil(
     context,
     MaterialPageRoute(
       builder: (context) => GroupedStoriesView(
```
I made it to clear the stack with paths.
Why do you think it is luggy compare the push?
Or maybe you can make PR with your propose and we compare.

**Comment by JSBmanD** [comment]
Because flutter need to redraw all the tree of widgets after closing the story but with stacking page over your it won't be redrawing. Also actually I can't get what is it making when you are closing the story. It's pushing '/' route?

**Comment by awaik** [comment]
Hi,
`pushAndRemoveUntil` changed to `push` and published.

> Also actually I can't get what is it making when you are closing the story. It's pushing '/' route?

Yes, here I copied Instagram behavior for the real app. If you need to push for the previous route in the app please create an issue, I try to do it within a week.
Or, you are welcome to make PR :)
