### ISSUE TITLE
Adding caption support to each slide

### ISSUE THREAD

**Issue by seanfarr788** [awaik/flutter_instagram_stories#9]
Greatly appreciate the word, just wondering like the original story_view whether there is a goal to add caption support? 

Many Thanks

**Comment by awaik** [comment]
Hello, thank you.
Yes, I would like to do it, but I don't want to do it as simple text.
Maybe you have ideas how it should look like?

**Comment by seanfarr788** [comment]
hmmm fair enough, well snapchat has this slightly darker background behind its text. Or it could be closer to facebook style with it being larger, white text overlayed. Not too sure, but I appreciate you responding :)

**Comment by seanfarr788** [comment]
Or I suppose it could just appear like a bottom modal, a bit like those "we use cookies" popups which come in from the bottom?

**Comment by awaik** [comment]
Thank you for your opinion. I'll think a little bit and add this feature within 1-2 weeks.

**Comment by seanfarr788** [comment]
Thank you Awaik, really looking forward to seeing it :)

**Comment by jonibolkvadze** [comment]
> Thank you Awaik, really looking forward to seeing it :)

Me too. 👍

**Comment by awaik** [comment]
Hi! Ok, will do during the weekend :)

**Comment by jonibolkvadze** [comment]
> Hi! Ok, will do during the weekend :)

Appreciate it. Thank you for this

**Comment by awaik** [comment]
I released it as version 0.1.4.
In case of any bugs please make the new issue. The documentation will be made next week, for now, you can see how to implement it in the changelog.
Thanks for the ideas. 👍

<img width="761" alt="Screenshot 2020-07-18 at 15 56 35" src="https://user-images.githubusercontent.com/5330807/87852994-52427180-c90f-11ea-8e4b-29a55e40336e.png">
